"""Tier a3 — the LLM ↔ Forge iteration loop.

This is the headline pipeline: intent → LLM emits code → Forge enforces
tier law → structured feedback → LLM iterates → … → certify ≥ threshold.

Forge is the architecture substrate.  An LLM (any provider) is the
generator.  Together they produce **architecturally-coherent** code in a
controlled loop where the LLM is held accountable to a strict layered
discipline.

Public API:
    run_iterate(intent, *, output, package, llm, ...) -> IterateReport
"""

from __future__ import annotations

import datetime as _dt
from pathlib import Path
from typing import Any

from ..a0_qk_constants.tier_names import TIER_NAMES
from ..a1_at_functions.certify_checks import certify
from ..a1_at_functions.forge_feedback import (
    compute_reuse_stats,
    pack_feedback,
    pack_initial_intent,
    parse_files_from_response,
    system_prompt,
)
from ..a1_at_functions.llm_client import LLMClient, resolve_default_client
from ..a1_at_functions.scaffold_pyproject import render_pyproject
from ..a1_at_functions.scaffold_starter import (
    render_gitignore, render_readme, render_tests_conftest, render_tests_init,
)
from ..a1_at_functions.scout_walk import harvest_repo
from ..a1_at_functions.tier_init_rebuild import rebuild_tier_inits
from ..a1_at_functions.transcript_log import TranscriptLog
from ..a1_at_functions.wire_check import scan_violations
from ..a2_mo_composites.manifest_store import ManifestStore

try:
    from .emergent_pipeline_integration import emergent_overlay_for_path
    _HAS_EMERGENT = True
except Exception:  # noqa: BLE001
    _HAS_EMERGENT = False


def _scaffold_package(output: Path, package: str, *,
                      intent: str = "") -> Path:
    """Scaffold a complete, pip-installable Python package skeleton.

    Creates: 5 tier directories with ``__init__.py``s, a real
    ``pyproject.toml`` rooted at ``output/``, ``README.md`` summarising
    the intent, ``.gitignore``, and ``tests/`` with a conftest that adds
    ``src/`` to ``sys.path``.  After this runs, ``pip install -e <output>``
    works and the LLM only has to emit the actual code.
    """
    pkg_root = output / "src" / package
    for tier in TIER_NAMES:
        d = pkg_root / tier
        d.mkdir(parents=True, exist_ok=True)
        (d / "__init__.py").write_text(f'"""{tier}."""\n', encoding="utf-8")
    (pkg_root / "__init__.py").write_text(
        f'"""{package} — generated by atomadic-forge iterate."""\n'
        f'__version__ = "0.0.1"\n',
        encoding="utf-8",
    )

    # Top-level scaffolds — only write if absent so re-runs don't clobber
    # an LLM-improved README.
    pyproject = output / "pyproject.toml"
    if not pyproject.exists():
        pyproject.write_text(
            render_pyproject(
                package=package,
                description=(intent or "")[:120].strip() or f"{package} package",
                console_script_target="a4_sy_orchestration.cli:main",
            ),
            encoding="utf-8",
        )
    readme = output / "README.md"
    if not readme.exists():
        readme.write_text(
            render_readme(package=package, intent=intent or "(unspecified)"),
            encoding="utf-8",
        )
    gi = output / ".gitignore"
    if not gi.exists():
        gi.write_text(render_gitignore(), encoding="utf-8")

    tests_dir = output / "tests"
    tests_dir.mkdir(exist_ok=True)
    init = tests_dir / "__init__.py"
    if not init.exists():
        init.write_text(render_tests_init(), encoding="utf-8")
    cf = tests_dir / "conftest.py"
    if not cf.exists():
        cf.write_text(render_tests_conftest(package=package), encoding="utf-8")

    return pkg_root


_PATH_REJECT_CHARS = ("<", ">", "|", "*", "?", '"', "\x00")


def _safe_path(rel: str) -> bool:
    """Reject placeholder/metachar/traversal paths the LLM may have emitted.

    Small models often echo template tokens like ``<pkg>`` or ``${name}``
    verbatim instead of substituting.  We refuse those instead of crashing
    on Windows or writing garbage files.
    """
    rel = rel.strip()
    if not rel:
        return False
    if any(ch in rel for ch in _PATH_REJECT_CHARS):
        return False
    if ".." in rel.replace("\\", "/").split("/"):
        return False
    if not (rel.endswith(".py") or rel.endswith(".md") or rel.endswith(".toml")):
        return False
    return True


def _write_files(output: Path, files: list[dict[str, str]]) -> list[str]:
    written: list[str] = []
    output_resolved = output.resolve()
    for f in files:
        rel = f.get("path", "").lstrip("/\\")
        if not _safe_path(rel):
            continue
        try:
            target = (output / rel).resolve()
            target.relative_to(output_resolved)  # prompt-injection / traversal guard
        except (ValueError, OSError):
            continue
        try:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(f.get("content", ""), encoding="utf-8")
        except OSError:
            continue
        written.append(str(target.relative_to(output_resolved).as_posix()))
    return written


def run_iterate(
    intent: str,
    *,
    output: Path,
    package: str = "generated",
    seed_repo: Path | None = None,
    llm: LLMClient | None = None,
    max_iterations: int = 5,
    target_score: float = 75.0,
    apply: bool = True,
) -> dict[str, Any]:
    """Run the LLM ↔ Forge loop.

    Termination: certify ≥ ``target_score`` AND wire PASS, OR ``max_iterations``
    exhausted, OR LLM emits an empty file list (signals "done").

    ``apply=False`` returns the planned prompt + initial response without
    writing files (useful for sanity-checking the prompt shape).
    """
    output = Path(output).resolve()
    output.mkdir(parents=True, exist_ok=True)
    llm = llm or resolve_default_client()
    pkg_root = (_scaffold_package(output, package, intent=intent)
                if apply else output / "src" / package)
    transcript = TranscriptLog(output) if apply else None

    # Optional seed catalog from a sibling repo.
    seed_catalog: list[dict] = []
    if seed_repo is not None and Path(seed_repo).exists():
        scout = harvest_repo(Path(seed_repo))
        seed_catalog = scout.get("symbols", [])

    turn_log: list[dict[str, Any]] = []
    history_files: list[str] = []
    sys_prompt = system_prompt()

    # ── Turn 0: initial intent ────────────────────────────────────────────
    prompt = pack_initial_intent(intent, package=package, seed_catalog=seed_catalog)
    if not apply:
        return {
            "schema_version": "atomadic-forge.iterate/v1",
            "applied": False,
            "package": package,
            "system_prompt": sys_prompt,
            "first_prompt": prompt,
            "llm": llm.name,
        }

    if transcript:
        transcript.append("system", sys_prompt, role="system", llm=llm.name)
        transcript.append("prompt", prompt, role="user", llm=llm.name,
                          extra={"turn": 0, "phase": "initial"})
    response = llm.call(prompt, system=sys_prompt)
    if transcript:
        transcript.append("response", response, role="assistant",
                          llm=llm.name, extra={"turn": 0})
    files = parse_files_from_response(response)
    parse_retried = False
    if not files and response.strip() and not response.strip().endswith("[]"):
        retry_prompt = (
            "Your previous response did not parse as a JSON array of "
            "`{path, content}` objects.  Output ONLY the JSON array "
            "literal, no prose, no markdown fences, no comments.  If you "
            "need to indicate completion, output the exact two characters "
            "`[]`.\n\n"
            "Re-emit your output now."
        )
        if transcript:
            transcript.append("prompt", retry_prompt, role="user",
                              llm=llm.name,
                              extra={"turn": 0, "phase": "parse-retry"})
        response = llm.call(retry_prompt, system=sys_prompt)
        if transcript:
            transcript.append("response", response, role="assistant",
                              llm=llm.name,
                              extra={"turn": 0, "phase": "parse-retry"})
        files = parse_files_from_response(response)
        parse_retried = True
    written = _write_files(output, files)
    if pkg_root.exists():
        rebuild_tier_inits(pkg_root)
    history_files.extend(written)
    turn_log.append({"turn": 0, "prompt": prompt, "files_written": written,
                     "raw_response_chars": len(response),
                     "parse_retried": parse_retried})

    # ── Iteration turns ────────────────────────────────────────────────────
    final_wire: dict[str, Any] | None = None
    final_cert: dict[str, Any] | None = None
    converged = False

    for turn in range(1, max_iterations + 1):
        wire = scan_violations(pkg_root)
        cert = certify(output, project=package, package=package)
        # Walk the *generated* package to compute reuse + emergent context.
        emitted_scout = harvest_repo(pkg_root) if pkg_root.exists() else None
        reuse = compute_reuse_stats(emitted_scout, seed_catalog)
        emergent: dict[str, Any] | None = None
        if _HAS_EMERGENT and pkg_root.exists():
            try:
                emergent = emergent_overlay_for_path(
                    output, phase="iterate", package=package,
                )
            except Exception:  # noqa: BLE001
                emergent = None
        final_wire, final_cert = wire, cert

        if wire["verdict"] == "PASS" and cert["score"] >= target_score:
            converged = True
            break

        feedback = pack_feedback(wire_report=wire, certify_report=cert,
                                   emergent_overlay=emergent,
                                   reuse_stats=reuse,
                                   iteration=turn)
        if transcript:
            transcript.append("prompt", feedback, role="user", llm=llm.name,
                              extra={"turn": turn, "phase": "iterate"})
        response = llm.call(feedback, system=sys_prompt)
        if transcript:
            transcript.append("response", response, role="assistant",
                              llm=llm.name, extra={"turn": turn})
        files = parse_files_from_response(response)
        if not files:
            turn_log.append({"turn": turn, "prompt_chars": len(feedback),
                             "files_written": [], "signal": "llm_done"})
            break
        written = _write_files(output, files)
        if pkg_root.exists():
            rebuild_tier_inits(pkg_root)
        history_files.extend(written)
        turn_log.append({"turn": turn, "prompt_chars": len(feedback),
                         "files_written": written,
                         "raw_response_chars": len(response)})

    report: dict[str, Any] = {
        "schema_version": "atomadic-forge.iterate/v1",
        "applied": True,
        "intent": intent,
        "package": package,
        "output_root": str(output),
        "llm": llm.name,
        "iterations": len(turn_log),
        "files_written_total": len(set(history_files)),
        "converged": converged,
        "final_wire": final_wire,
        "final_certify": {
            "score": (final_cert or {}).get("score", 0),
            "issues": (final_cert or {}).get("issues", []),
        },
        "transcript": turn_log,
        "transcript_log_path": (str(transcript.path) if transcript else None),
        "generated_at_utc": _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds"),
    }
    ManifestStore(output).save("iterate", report)
    return report
