"""Tier a3 — Forge feature orchestrators.

These wire the a1 helpers + a2 composites into the user-facing verbs:
``recon`` (scout + emergent overlay), ``cherry`` (cherry-pick),
``finalize`` (assimilate + wire + certify), and ``auto`` (the whole chain).

Every entry point returns a structured dict so downstream tools can pipe
output reliably.  When ``apply=False`` the pipeline runs in dry-run mode —
nothing is written to disk except into the project's ``.atomadic-forge/``
manifest store.
"""

from __future__ import annotations

import hashlib
import json
import shutil
from pathlib import Path
from typing import Any, Iterable

from ..a0_qk_constants.tier_names import TIER_NAMES
from ..a1_at_functions.cherry_pick import select_items
from ..a1_at_functions.certify_checks import certify
from ..a1_at_functions.scout_walk import harvest_repo
from ..a1_at_functions.wire_check import scan_violations
from ..a2_mo_composites.manifest_store import ManifestStore


_STATUS_TEMPLATE = """# Atomadic Forge — Assimilation Status

This directory was produced by ``forge auto`` / ``forge finalize``.  It is
**bootstrapped material**, not a finished product.

## What's here
- 5-tier monadic layout (``a0_qk_constants/`` … ``a4_sy_orchestration/``)
- Symbols ingested from {source_count} source repo(s)
- {component_count} components emitted
- Digest: ``{digest}``

## What's still required before shipping
1. **Integration tests** against real inputs — the bootstrap copies code
   verbatim where possible, but cross-symbol semantics (two ``User`` classes,
   two ``authenticate`` flows) need human reconciliation.
2. **Runtime configuration** — secrets, environment variables, DB URLs.
3. **Observability** — logging, metrics, error reporting.
4. **Wire enforcement** — run ``forge wire`` and address any violations.
5. **Certification** — ``forge certify`` should hit ≥ 75 before public use.

## Provenance
Source repos: {source_list}

Generated by atomadic-forge {version}.
"""


def run_recon(target: Path, *, store_manifest: bool = True) -> dict[str, Any]:
    """``forge recon`` — scout walk + persist scout.json under .atomadic-forge/."""
    target = Path(target).resolve()
    report = harvest_repo(target)
    if store_manifest:
        ManifestStore(target).save("scout", report)
    return report


def run_cherry(target: Path, *, names: Iterable[str] | None = None,
               pick_all: bool = False, only_tier: str | None = None,
               store_manifest: bool = True) -> dict[str, Any]:
    """``forge cherry`` — derive a cherry-pick manifest from the latest scout."""
    target = Path(target).resolve()
    store = ManifestStore(target)
    scout = store.load("scout") or harvest_repo(target)
    if not store.load("scout") and store_manifest:
        store.save("scout", scout)
    manifest = select_items(scout, names=names, pick_all=pick_all,
                            only_tier=only_tier)
    if store_manifest:
        store.save("cherry", manifest)
    return manifest


def run_finalize(*, target: Path, output: Path, package: str = "absorbed",
                 cherry_manifest: dict[str, Any] | None = None,
                 apply: bool = False,
                 on_conflict: str = "rename") -> dict[str, Any]:
    """``forge finalize`` — assimilate + wire + certify.

    ``on_conflict`` resolves duplicate qualnames across roots:
    ``rename``  (default) appends a suffix
    ``first``   keep first-seen
    ``last``    keep last-seen
    ``fail``    raise ValueError
    """
    target = Path(target).resolve()
    output = Path(output).resolve()
    if cherry_manifest is None:
        cherry_manifest = run_cherry(target, pick_all=True)

    pkg_root = output / "src" / package
    if apply:
        for tier in TIER_NAMES:
            (pkg_root / tier).mkdir(parents=True, exist_ok=True)
            (pkg_root / tier / "__init__.py").write_text(
                f'"""{tier}."""\n', encoding="utf-8",
            )
        (pkg_root / "__init__.py").write_text(
            f'"""Absorbed package — bootstrapped by atomadic-forge."""\n'
            f'__version__ = "0.0.1"\n',
            encoding="utf-8",
        )

    items = cherry_manifest.get("items", [])
    seen_targets: dict[Path, dict] = {}  # target file → originating item
    components_emitted = 0
    tier_dist: dict[str, int] = {}
    skipped: list[dict] = []

    for it in items:
        qual = it["qualname"]
        tier = it["target_tier"]
        # Find the source file from the scout report
        scout = ManifestStore(target).load("scout") or {}
        sym = next((s for s in scout.get("symbols", []) if s["qualname"] == qual),
                    None)
        if sym is None:
            skipped.append({"qualname": qual, "reason": "not in scout"})
            continue
        src_file = target / sym["file"]
        if not src_file.exists():
            skipped.append({"qualname": qual, "reason": "source file gone"})
            continue
        slug = qual.replace(".", "_").lower()
        target_dir = pkg_root / tier
        target_file = target_dir / f"{slug}.py"

        if target_file in seen_targets:
            if on_conflict == "fail":
                raise ValueError(f"conflict on {target_file}: {qual} vs "
                                 f"{seen_targets[target_file]['qualname']}")
            if on_conflict == "first":
                skipped.append({"qualname": qual, "reason": "first-wins"})
                continue
            if on_conflict == "last":
                pass  # fall through, overwrite
            if on_conflict == "rename":
                target_file = target_dir / f"{slug}__alt.py"

        if apply:
            target_dir.mkdir(parents=True, exist_ok=True)
            try:
                shutil.copyfile(src_file, target_file)
            except OSError as exc:
                skipped.append({"qualname": qual, "reason": f"copy failed: {exc}"})
                continue
        seen_targets[target_file] = it
        components_emitted += 1
        tier_dist[tier] = tier_dist.get(tier, 0) + 1

    digest = hashlib.sha256(
        json.dumps([{**it, "_": "x"} for it in items], sort_keys=True).encode()
    ).hexdigest()[:16]

    if apply:
        status = _STATUS_TEMPLATE.format(
            source_count=1,
            component_count=components_emitted,
            digest=digest,
            source_list=str(target),
            version="0.1.0",
        )
        (output / "STATUS.md").write_text(status, encoding="utf-8")

    wire_report = scan_violations(pkg_root) if apply else {
        "verdict": "DRY_RUN", "violation_count": 0, "violations": []
    }
    cert = certify(output, project=package, package=package) if apply else {
        "score": 0, "issues": ["dry-run — re-run with --apply to certify"],
        "schema_version": "atomadic-forge.certify/v1",
    }

    report = {
        "schema_version": "atomadic-forge.assimilate/v1",
        "target_root": str(output),
        "source_repos": [str(target)],
        "components_emitted": components_emitted,
        "tier_distribution": tier_dist,
        "skipped": skipped,
        "digest": digest,
        "wire": wire_report,
        "certify": cert,
        "applied": apply,
        "on_conflict": on_conflict,
    }
    if apply:
        ManifestStore(output).save("assimilate", report)
    return report


def run_auto(*, target: Path, output: Path, package: str = "absorbed",
             apply: bool = False, on_conflict: str = "rename") -> dict[str, Any]:
    """``forge auto`` — the flagship single-command pipeline.

    Runs: scout → cherry-pick (all) → finalize (assimilate + wire + certify).
    Always returns a structured report.  Set ``apply=True`` to actually write
    files; otherwise it's a deterministic dry-run.
    """
    scout = run_recon(target)
    cherry = run_cherry(target, pick_all=True)
    final = run_finalize(target=target, output=output, package=package,
                          cherry_manifest=cherry, apply=apply,
                          on_conflict=on_conflict)
    return {
        "schema_version": "atomadic-forge.auto/v1",
        "scout": {
            "symbol_count": scout["symbol_count"],
            "tier_distribution": scout["tier_distribution"],
            "recommendations": scout["recommendations"],
        },
        "cherry": {"items": len(cherry["items"])},
        "finalize": final,
        "applied": apply,
    }
