"""Tier verification — Codex-3: plan persistence + step/apply.

Three layers:
  * a2 PlanStore round-trips, idempotent ids, per-card events
  * a3 forge_plan_apply routes architectural F0042 cards through
    forge enforce + writes the docs README for F0050; both record
    their outcome to the plan store
  * a4 CLI verbs (plan-list, plan-show, plan-step, plan-apply)
    round-trip a plan generated by `forge plan --save`
  * MCP tools auto_step / auto_apply dispatch via a1↔a3 injection
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest
import typer.testing

from atomadic_forge.a2_mo_composites.plan_store import (
    PlanStore,
    compute_plan_id,
)
# Importing a3.mcp_server wires auto_step / auto_apply handlers.
import atomadic_forge.a3_og_features.mcp_server  # noqa: F401
from atomadic_forge.a1_at_functions.agent_plan_emitter import emit_agent_plan
from atomadic_forge.a1_at_functions.mcp_protocol import dispatch_request
from atomadic_forge.a3_og_features.forge_plan_apply import (
    apply_all_applyable,
    apply_card,
)
from atomadic_forge.a4_sy_orchestration.cli import app

runner = typer.testing.CliRunner()


def _make_violation_tree(tmp_path: Path) -> Path:
    pkg = tmp_path / "pkg"
    a1 = pkg / "a1_at_functions"; a1.mkdir(parents=True)
    a3 = pkg / "a3_og_features"; a3.mkdir(parents=True)
    (a3 / "feat.py").write_text(
        '"""a3."""\nclass F:\n    pass\n', encoding="utf-8")
    (a1 / "h.py").write_text(
        "from ..a3_og_features.feat import F\n", encoding="utf-8")
    return pkg


# ---- a2 PlanStore -------------------------------------------------------

def test_compute_plan_id_is_deterministic_under_volatile_fields():
    """Two emits of the same plan with different generated_at_utc /
    saved_at_utc must yield the same id (re-emit-safe)."""
    plan_a = emit_agent_plan(
        project_root="/tmp/x", goal="ship",
        wire_report={"verdict": "PASS", "violation_count": 0,
                      "auto_fixable": 0, "violations": [],
                      "schema_version": "atomadic-forge.wire/v1"},
        certify_report={
            "score": 100.0, "documentation_complete": True,
            "tests_present": True, "tier_layout_present": True,
            "no_upward_imports": True, "issues": [],
            "schema_version": "atomadic-forge.certify/v1",
        },
    )
    plan_b = emit_agent_plan(
        project_root="/tmp/x", goal="ship",
        wire_report={"verdict": "PASS", "violation_count": 0,
                      "auto_fixable": 0, "violations": [],
                      "schema_version": "atomadic-forge.wire/v1"},
        certify_report={
            "score": 100.0, "documentation_complete": True,
            "tests_present": True, "tier_layout_present": True,
            "no_upward_imports": True, "issues": [],
            "schema_version": "atomadic-forge.certify/v1",
        },
    )
    # The plans differ in generated_at_utc but should hash identically.
    assert plan_a["generated_at_utc"] != plan_b["generated_at_utc"] \
        or plan_a == plan_b
    assert compute_plan_id(plan_a) == compute_plan_id(plan_b)


def test_plan_store_round_trip(tmp_path):
    plan = emit_agent_plan(
        project_root=str(tmp_path), goal="ship",
        certify_report={"score": 50.0, "documentation_complete": False,
                         "tests_present": True, "tier_layout_present": True,
                         "no_upward_imports": True, "issues": [],
                         "schema_version": "atomadic-forge.certify/v1"},
        package="demo",
    )
    store = PlanStore(tmp_path)
    plan_id = store.save_plan(plan)
    loaded = store.load_plan(plan_id)
    assert loaded is not None
    assert loaded["id"] == plan_id
    assert loaded["goal"] == plan["goal"]
    plans = store.list_plans()
    assert len(plans) == 1
    assert plans[0]["plan_id"] == plan_id


def test_plan_store_records_card_events(tmp_path):
    plan = emit_agent_plan(
        project_root=str(tmp_path), goal="ship",
        certify_report={"score": 0.0, "documentation_complete": False,
                         "tests_present": True, "tier_layout_present": True,
                         "no_upward_imports": True, "issues": [],
                         "schema_version": "atomadic-forge.certify/v1"},
        package="demo",
    )
    store = PlanStore(tmp_path)
    plan_id = store.save_plan(plan)
    card_id = plan["top_actions"][0]["id"]
    store.record_card_event(plan_id, card_id=card_id,
                              status="dry_run", detail={"x": 1})
    store.record_card_event(plan_id, card_id=card_id,
                              status="applied", detail={"y": 2})
    assert store.card_status(plan_id, card_id) == "applied"
    state = store.load_state(plan_id)
    assert len(state["events"]) == 2


def test_plan_store_skips_corrupt_plan_files(tmp_path):
    d = tmp_path / ".atomadic-forge" / "plans"
    d.mkdir(parents=True)
    (d / "good.json").write_text(json.dumps({
        "id": "good", "verdict": "PASS", "goal": "g", "mode": "improve",
        "action_count": 0, "applyable_count": 0,
        "saved_at_utc": "2026-04-29T00:00:00Z",
    }), encoding="utf-8")
    (d / "broken.json").write_text("this-is-not-json", encoding="utf-8")
    plans = PlanStore(tmp_path).list_plans()
    ids = {p["plan_id"] for p in plans}
    assert "good" in ids
    assert "broken" not in ids


# ---- a3 forge_plan_apply -----------------------------------------------

def test_apply_card_F0042_routes_through_enforce(tmp_path):
    pkg = _make_violation_tree(tmp_path)
    plan = emit_agent_plan(
        project_root=str(pkg), goal="ship",
        wire_report={"schema_version": "atomadic-forge.wire/v1",
                      "verdict": "FAIL", "violation_count": 1,
                      "auto_fixable": 1,
                      "violations": [
                          {"file": "a1_at_functions/h.py",
                           "from_tier": "a1_at_functions",
                           "to_tier": "a3_og_features",
                           "imported": "F", "language": "python",
                           "f_code": "F0042", "proposed_fix": ""}]},
        package="pkg",
    )
    plan_id = PlanStore(pkg).save_plan(plan)
    plan["id"] = plan_id
    card_id = next(c["id"] for c in plan["top_actions"]
                    if "F0042" in (c.get("related_fcodes") or []))
    # Dry-run: file should NOT move.
    dry = apply_card(pkg, plan, card_id, apply=False)
    assert dry["status"] == "dry_run"
    assert (pkg / "a1_at_functions" / "h.py").exists()
    # Apply: enforce should move + reduce violations to 0.
    real = apply_card(pkg, plan, card_id, apply=True)
    assert real["status"] == "applied"
    assert real["detail"]["post_violations"] == 0
    assert (pkg / "a3_og_features" / "h.py").exists()
    assert not (pkg / "a1_at_functions" / "h.py").exists()
    # Outcome is in the plan-state file.
    assert PlanStore(pkg).card_status(plan_id, card_id) == "applied"


def test_apply_card_F0050_writes_readme(tmp_path):
    plan = emit_agent_plan(
        project_root=str(tmp_path), goal="ship",
        certify_report={"score": 0.0, "documentation_complete": False,
                         "tests_present": True, "tier_layout_present": True,
                         "no_upward_imports": True, "issues": [],
                         "schema_version": "atomadic-forge.certify/v1"},
        package="demo",
    )
    plan_id = PlanStore(tmp_path).save_plan(plan)
    plan["id"] = plan_id
    card_id = next(c["id"] for c in plan["top_actions"]
                    if "F0050" in (c.get("related_fcodes") or []))
    real = apply_card(tmp_path, plan, card_id, apply=True)
    assert real["status"] == "applied"
    readme = tmp_path / "README.md"
    assert readme.exists()
    assert "Stub README written by `forge plan-apply`" in readme.read_text(
        encoding="utf-8")


def test_apply_card_unknown_id(tmp_path):
    plan = emit_agent_plan(
        project_root=str(tmp_path), goal="ship",
        certify_report={"score": 100.0, "documentation_complete": True,
                         "tests_present": True, "tier_layout_present": True,
                         "no_upward_imports": True, "issues": [],
                         "schema_version": "atomadic-forge.certify/v1"},
    )
    PlanStore(tmp_path).save_plan(plan)
    out = apply_card(tmp_path, plan, "no-such-card-id")
    assert out["status"] == "failed"


def test_apply_card_review_only_skipped(tmp_path):
    """A card with applyable=False (e.g. F0040) is recorded as
    skipped without any filesystem mutation."""
    plan = emit_agent_plan(
        project_root=str(tmp_path), goal="ship",
        wire_report={"schema_version": "atomadic-forge.wire/v1",
                      "verdict": "FAIL", "violation_count": 1,
                      "auto_fixable": 0,
                      "violations": [
                          {"file": "a0_qk_constants/c.py",
                           "from_tier": "a0_qk_constants",
                           "to_tier": "a3_og_features",
                           "imported": "F", "language": "python",
                           "f_code": "F0040", "proposed_fix": ""}]},
    )
    plan_id = PlanStore(tmp_path).save_plan(plan)
    plan["id"] = plan_id
    card = plan["top_actions"][0]
    assert card["applyable"] is False
    out = apply_card(tmp_path, plan, card["id"], apply=True)
    assert out["status"] == "skipped"


def test_apply_all_applyable_halts_on_failure(tmp_path):
    """With one applyable card pointing at a non-existent write_scope,
    apply_all_applyable returns halted_on='failed'."""
    plan: dict = {
        "schema_version": "atomadic-forge.agent_plan/v1",
        "id": "test-plan",
        "verdict": "FAIL", "goal": "ship", "mode": "improve",
        "project_root": str(tmp_path),
        "top_actions": [{
            "schema_version": "atomadic-forge.agent_action/v1",
            "id": "broken-card", "kind": "architectural",
            "title": "broken", "why": "",
            "risk": "low", "applyable": True,
            "write_scope": [],   # empty -> handler returns 'failed'
            "commands": [], "related_fcodes": ["F0042"],
            "next_command": "", "sample_path": None,
            "score_delta_estimate": 0,
        }],
        "action_count": 1, "applyable_count": 1, "next_command": "",
        "sources": {},
    }
    PlanStore(tmp_path).save_plan(plan)
    rep = apply_all_applyable(tmp_path, plan, apply=True)
    assert rep["halted_on"] == "failed"
    assert rep["applied_count"] == 0


# ---- CLI verbs ----------------------------------------------------------

def test_cli_plan_save_and_list(tmp_path):
    pkg = _make_violation_tree(tmp_path)
    result = runner.invoke(app, ["plan", str(pkg), "--save", "--json"])
    assert result.exit_code == 0
    plan = json.loads(result.stdout)
    plan_id = plan["id"]
    # Now list_cmd should see it.
    listing = runner.invoke(
        app, ["plan-list", "--project", str(pkg), "--json"])
    assert listing.exit_code == 0
    data = json.loads(listing.stdout)
    assert any(p["plan_id"] == plan_id for p in data["plans"])


def test_cli_plan_show_missing_id_errors(tmp_path):
    result = runner.invoke(
        app, ["plan-show", "ghost-id", "--project", str(tmp_path)])
    assert result.exit_code != 0


def test_cli_plan_step_dry_run_then_apply(tmp_path):
    pkg = _make_violation_tree(tmp_path)
    save = runner.invoke(app, ["plan", str(pkg), "--save", "--json"])
    plan = json.loads(save.stdout)
    plan_id = plan["id"]
    card_id = next(c["id"] for c in plan["top_actions"]
                    if c.get("applyable"))
    dry = runner.invoke(
        app, ["plan-step", plan_id, card_id,
              "--project", str(pkg), "--json"])
    assert dry.exit_code == 0
    assert json.loads(dry.stdout)["status"] == "dry_run"
    real = runner.invoke(
        app, ["plan-step", plan_id, card_id,
              "--project", str(pkg), "--apply", "--json"])
    assert real.exit_code == 0
    assert json.loads(real.stdout)["status"] == "applied"


def test_cli_plan_apply_all_dry_run(tmp_path):
    pkg = _make_violation_tree(tmp_path)
    save = runner.invoke(app, ["plan", str(pkg), "--save", "--json"])
    plan_id = json.loads(save.stdout)["id"]
    res = runner.invoke(
        app, ["plan-apply", plan_id, "--project", str(pkg), "--json"])
    assert res.exit_code == 0
    rep = json.loads(res.stdout)
    assert rep["schema_version"] == "atomadic-forge.plan_apply_all/v1"
    assert rep["applied_count"] == 0  # dry run by default


# ---- MCP auto_step / auto_apply -----------------------------------------

def test_mcp_auto_step_dispatches(tmp_path):
    pkg = _make_violation_tree(tmp_path)
    plan = emit_agent_plan(
        project_root=str(pkg), goal="ship",
        wire_report={"schema_version": "atomadic-forge.wire/v1",
                      "verdict": "FAIL", "violation_count": 1,
                      "auto_fixable": 1,
                      "violations": [
                          {"file": "a1_at_functions/h.py",
                           "from_tier": "a1_at_functions",
                           "to_tier": "a3_og_features",
                           "imported": "F", "language": "python",
                           "f_code": "F0042", "proposed_fix": ""}]},
    )
    plan_id = PlanStore(pkg).save_plan(plan)
    card_id = next(c["id"] for c in plan["top_actions"] if c.get("applyable"))
    resp = dispatch_request(
        {"jsonrpc": "2.0", "id": 1, "method": "tools/call",
         "params": {"name": "auto_step",
                    "arguments": {"project": str(pkg),
                                   "plan_id": plan_id,
                                   "card_id": card_id,
                                   "apply": False}}},
        project_root=pkg,
    )
    body = json.loads(resp["result"]["content"][0]["text"])
    assert body["status"] == "dry_run"


def test_mcp_auto_apply_dispatches(tmp_path):
    pkg = _make_violation_tree(tmp_path)
    plan = emit_agent_plan(
        project_root=str(pkg), goal="ship",
        wire_report={"schema_version": "atomadic-forge.wire/v1",
                      "verdict": "FAIL", "violation_count": 1,
                      "auto_fixable": 1,
                      "violations": [
                          {"file": "a1_at_functions/h.py",
                           "from_tier": "a1_at_functions",
                           "to_tier": "a3_og_features",
                           "imported": "F", "language": "python",
                           "f_code": "F0042", "proposed_fix": ""}]},
    )
    plan_id = PlanStore(pkg).save_plan(plan)
    resp = dispatch_request(
        {"jsonrpc": "2.0", "id": 1, "method": "tools/call",
         "params": {"name": "auto_apply",
                    "arguments": {"project": str(pkg),
                                   "plan_id": plan_id,
                                   "apply": False}}},
        project_root=pkg,
    )
    body = json.loads(resp["result"]["content"][0]["text"])
    assert body["schema_version"] == "atomadic-forge.plan_apply_all/v1"
    assert body["plan_id"] == plan_id


def test_mcp_auto_step_unknown_plan(tmp_path):
    resp = dispatch_request(
        {"jsonrpc": "2.0", "id": 1, "method": "tools/call",
         "params": {"name": "auto_step",
                    "arguments": {"project": str(tmp_path),
                                   "plan_id": "ghost", "card_id": "ghost"}}},
        project_root=tmp_path,
    )
    body = json.loads(resp["result"]["content"][0]["text"])
    assert body["status"] == "failed"
