"""
Auto-generated by Commandsmith — do NOT hand-edit.
Run ``atomadic-forge commandsmith sync`` to refresh.
"""

from __future__ import annotations

import typer


def register_all(app: typer.Typer) -> None:
    """Register every Commandsmith-discovered command on ``app``."""
    from atomadic_forge.commands.chat import app as _app_chat
    app.add_typer(_app_chat, name='chat', help='Chat with a Forge-aware AI copilot over optional repo context.', hidden=False)
    from atomadic_forge.commands.commandsmith import app as _app_commandsmith
    app.add_typer(_app_commandsmith, name='commandsmith', help='``atomadic-forge commandsmith`` — manage the auto-wired CLI command registry.', hidden=False)
    from atomadic_forge.commands.config_cmd import app as _app_config
    app.add_typer(_app_config, name='config', help='Configure Atomadic Forge — setup wizard + config management.', hidden=False)
    from atomadic_forge.commands.demo import app as _app_demo
    app.add_typer(_app_demo, name='demo', help='One-shot launch-video verb: preset evolve + DEMO.md artifact.', hidden=False)
    from atomadic_forge.commands.emergent import app as _app_emergent
    app.add_typer(_app_emergent, name='emergent', help='Synthesise new feature candidates from existing components.', hidden=False)
    from atomadic_forge.commands.emergent_then_synergy import app as _app_emergent_then_synergy
    app.add_typer(_app_emergent_then_synergy, name='emergent-then-synergy', help='Run emergent to emit a JSON artifact, then feed it to synergy for the next phase.', hidden=False)
    from atomadic_forge.commands.evolve import app as _app_evolve
    app.add_typer(_app_evolve, name='evolve', help="Recursive self-improvement: run iterate N times, each round seeded by the previous round's growing catalog.", hidden=False)
    from atomadic_forge.commands.evolve_then_iterate import app as _app_evolve_then_iterate
    app.add_typer(_app_evolve_then_iterate, name='evolve-then-iterate', help='Run evolve to emit a JSON artifact, then feed it to iterate for the next phase.', hidden=False)
    from atomadic_forge.commands.feature_then_emergent import app as _app_feature_then_emergent
    app.add_typer(_app_feature_then_emergent, name='feature-then-emergent', help='Run any feature, then fan its JSON output into emergent scan to surface novel compositions.', hidden=False)
    from atomadic_forge.commands.iterate import app as _app_iterate
    app.add_typer(_app_iterate, name='iterate', help='Architecturally-coherent code generation: LLM emits, Forge enforces, loop iterates until certify clears.', hidden=False)
    from atomadic_forge.commands.synergy import app as _app_synergy
    app.add_typer(_app_synergy, name='synergy', help="Find feature/CLI synergies (producer-consumer pairs that aren't wired together) and optionally implement adapters.", hidden=False)
    from atomadic_forge.commands.synergy_then_emergent import app as _app_synergy_then_emergent
    app.add_typer(_app_synergy_then_emergent, name='synergy-then-emergent', help='Run synergy to emit a JSON artifact, then feed it to emergent for the next phase.', hidden=False)
