"""Tier a1 — pure renderers for the Commandsmith CLI registry.

Three renderers:

* :func:`render_registry_module` — emits the ``atomadic_forge.commands._registry``
  Python source that auto-imports each discovered command module and wires
  it onto the supplied Typer app.

* :func:`render_command_doc` — emits a Markdown page for a single command
  card.

* :func:`render_command_index` — emits ``docs/commands/INDEX.md`` listing
  every registered command.

* :func:`render_wrapper_module` — emits a Python source file that wraps a
  bare class (e.g. an assimilated ``CherryPicker``) in a Typer subcommand
  group, so newly assimilated features can be invoked from the CLI without
  hand-coded glue.

All four are pure: they take cards and return strings.  No I/O.
"""

from __future__ import annotations

from collections.abc import Iterable

from ..a0_qk_constants.commandsmith_types import (
    CommandSignatureCard,
    RegisteredCommandCard,
)

_REGISTRY_HEADER = '''"""
Auto-generated by Commandsmith — do NOT hand-edit.
Run ``atomadic-forge commandsmith sync`` to refresh.
"""

from __future__ import annotations

import typer


'''


def render_registry_module(cards: Iterable[RegisteredCommandCard]) -> str:
    """Render an importable module that registers every card on a Typer app."""
    cards = list(cards)
    imports: list[str] = []
    body: list[str] = []
    for card in cards:
        mod = card["module"]
        imports.append(f"from {mod} import *  # noqa: F401,F403 — exported via {card['surface']}")
        # We import the module by full name as alias so different surfaces work
        # together; collisions are avoided because names are distinct verbs.
    if not cards:
        body.append("    pass  # no commands discovered")
    else:
        body.append("    \"\"\"Register every Commandsmith-discovered command on ``app``.\"\"\"")
        for card in cards:
            mod = card["module"]
            verb = card["name"]
            help_text = card["help_text"].replace('"""', "'''")
            hidden = card["hidden"]
            if card["surface"] == "typer_app":
                body.append(
                    f"    from {mod} import app as _app_{verb.replace('-', '_')}"
                )
                body.append(
                    f"    app.add_typer(_app_{verb.replace('-', '_')}, name={verb!r}, "
                    f"help={help_text!r}, hidden={hidden!r})"
                )
            elif card["surface"] == "register_fn":
                body.append(f"    from {mod} import register as _reg_{verb.replace('-', '_')}")
                body.append(
                    f"    _sub_{verb.replace('-', '_')} = typer.Typer(name={verb!r}, "
                    f"help={help_text!r})"
                )
                body.append(
                    f"    _reg_{verb.replace('-', '_')}(_sub_{verb.replace('-', '_')})"
                )
                body.append(
                    f"    app.add_typer(_sub_{verb.replace('-', '_')}, name={verb!r}, "
                    f"hidden={hidden!r})"
                )
            elif card["surface"] == "wrapped_class":
                wrapper_mod = f"{mod}_cli"
                body.append(
                    f"    from {wrapper_mod} import app as _wrap_{verb.replace('-', '_')}"
                )
                body.append(
                    f"    app.add_typer(_wrap_{verb.replace('-', '_')}, name={verb!r}, "
                    f"help={help_text!r}, hidden={hidden!r})"
                )
    src = _REGISTRY_HEADER
    src += "def register_all(app: typer.Typer) -> None:\n"
    src += "\n".join(body) + "\n"
    return src


def render_command_doc(card: RegisteredCommandCard) -> str:
    """Render a Markdown page describing one command."""
    lines = [
        f"# `atomadic-forge {card['name']}`",
        "",
        f"_{card['help_text']}_" if card["help_text"] else "",
        "",
        f"- **Module**: `{card['module']}`",
        f"- **Surface**: `{card['surface']}`",
        f"- **Source root**: `{card['source_root']}`",
        f"- **Hidden**: `{card['hidden']}`",
        "",
    ]
    if card["sub_commands"]:
        lines.append("## Sub-commands")
        lines.append("")
        for sc in card["sub_commands"]:
            lines.append(f"### `{sc['name']}`")
            lines.append("")
            if sc["docstring"]:
                lines.append(sc["docstring"])
                lines.append("")
            if sc["parameters"]:
                lines.append("Parameters:")
                lines.append("")
                for p in sc["parameters"]:
                    lines.append(f"- `{p}`")
                lines.append("")
            lines.append(f"Returns: `{sc['return_type']}`")
            lines.append("")
    return "\n".join(line for line in lines if line is not None) + "\n"


def render_command_index(cards: Iterable[RegisteredCommandCard]) -> str:
    """Render docs/commands/INDEX.md."""
    cards = sorted(cards, key=lambda c: c["name"])
    lines = ["# ASS-ADE Commands", "", "Auto-generated index. One row per top-level CLI verb.", "",
             "| Verb | Help | Source | Surface |",
             "|------|------|--------|---------|"]
    for c in cards:
        help_short = c["help_text"].replace("|", "\\|") or "_(no help)_"
        lines.append(
            f"| `{c['name']}` | {help_short} | `{c['source_root']}` | `{c['surface']}` |"
        )
    return "\n".join(lines) + "\n"


def render_wrapper_module(
    *,
    target_module: str,
    target_class: str,
    command_name: str,
    sub_commands: list[CommandSignatureCard],
    help_text: str = "",
    init_params: list[str] | None = None,
    auto_scan: str | None = None,
) -> str:
    """Emit a wrapper Python module wrapping a class as a Typer subcommand group.

    Generated app structure::

        app = typer.Typer()
        @app.callback() — accepts __init__ params, builds an instance, stashes it
                          on ``ctx.obj``.  Optionally auto-invokes a "warm-up"
                          method (e.g. ``scan_repo``) before subcommands.
        @app.command("verb") — pulls instance off ctx.obj, calls the method.
    """
    safe_help = help_text.replace('"""', "'''")
    init_params = init_params or []
    init_sig, init_fwd = _build_typer_args(init_params)
    has_init_args = bool(init_fwd)

    lines = [
        '"""',
        f"Auto-generated wrapper for {target_module}.{target_class}.",
        "",
        f"Run ``atomadic-forge {command_name} <method>`` to invoke methods on this class.",
        "Re-emit with ``atomadic-forge commandsmith wrap`` after the source changes.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import json",
        "from pathlib import Path  # noqa: F401  — used by some auto-generated annotations",
        "import typer",
        "",
        f"from {target_module} import {target_class}",
        "",
        f"COMMAND_NAME = {command_name!r}",
        f"COMMAND_HELP = {safe_help!r}",
        "",
        f'app = typer.Typer(no_args_is_help=True, help={safe_help!r})',
        "",
    ]

    # Callback that builds the instance.  Always emitted so subcommands can
    # share the instance via ctx.obj.
    cb_args = "ctx: typer.Context"
    if init_sig:
        cb_args += ", " + init_sig
    lines.extend([
        "@app.callback()",
        f"def _build({cb_args}) -> None:",
        f'    """Construct an instance of {target_class} for this invocation."""',
    ])
    if has_init_args:
        lines.append(f"    instance = {target_class}({init_fwd})")
    else:
        lines.append(f"    instance = {target_class}()")
    if auto_scan:
        lines.append(f"    # auto-warm-up: call {auto_scan}() so subcommands see populated state")
        lines.append("    try:")
        lines.append(f"        instance.{auto_scan}()")
        lines.append("    except Exception:")
        lines.append("        pass")
    lines.append("    ctx.obj = instance")
    lines.append("")

    if not sub_commands:
        lines.extend([
            "@app.command('show')",
            "def _show(ctx: typer.Context) -> None:",
            f'    """No public methods detected — show the {target_class} repr."""',
            "    typer.echo(repr(ctx.obj))",
        ])

    for sc in sub_commands:
        if sc["name"] in {"__init__"}:
            continue
        verb = sc["name"].replace("_", "-")
        py_args, fwd_args = _build_typer_args(sc["parameters"])
        full_sig = "ctx: typer.Context"
        if py_args:
            full_sig += ", " + py_args
        doc = sc["docstring"] or f"Invoke {target_class}.{sc['name']}."
        lines.extend([
            f"@app.command({verb!r})",
            f"def _{sc['name']}({full_sig}) -> None:",
            f'    """{doc}"""',
            f"    result = ctx.obj.{sc['name']}({fwd_args})",
            "    if result is not None:",
            "        try:",
            "            typer.echo(json.dumps(result, indent=2, default=str))",
            "        except (TypeError, ValueError):",
            "            typer.echo(str(result))",
            "",
        ])
    return "\n".join(lines) + "\n"


def _build_typer_args(parameters: list[str]) -> tuple[str, str]:
    """Build (python signature args, forward-call args) from parameter strings.

    Drops ``self``.  Falls back to ``str`` for unknown annotations.
    """
    sig_parts: list[str] = []
    fwd_parts: list[str] = []
    for p in parameters:
        name, _, ann = p.partition(":")
        name = name.strip()
        ann = ann.strip() or "str"
        if name in ("self", "cls"):
            continue
        if ann not in ("int", "float", "bool", "str", "Path", "list", "dict"):
            ann = "str"
        sig_parts.append(f"{name}: {ann}")
        fwd_parts.append(name)
    return ", ".join(sig_parts), ", ".join(fwd_parts)
