"""Tier a4 — ``forge login`` interactive subscription-key capture.

Golden Path Lane C W5 deliverable. Pairs with the
``a3_og_features/mcp_server.py`` subscription gate: that gate reads
``FORGE_API_KEY`` from the environment on every ``tools/call`` and
rejects the call if the key is missing, malformed, or revoked. This
verb is how a real human gets that key onto their machine in the first
place.

Flow:
  1. Print the upgrade URL (``https://atomadic.tech/forge#account``)
     so the user can grab a fresh ``fk_live_*`` key from the
     dashboard.
  2. Prompt for the key (echo hidden so it doesn't end up in shell
     history).
  3. Validate shape locally (must start with ``fk_live_``).
  4. Hit the verify endpoint via ``ForgeAuthClient`` to confirm the
     key is currently active. Soft-fail on offline (we still WRITE
     the key, but tell the user verification is pending).
  5. Write the key to ``~/.atomadic-forge/credentials.toml`` with
     POSIX mode 0o600 so it isn't world-readable.
  6. Print confirmation including the email + plan returned by the
     verify endpoint.

Why a4: the verb composes a1 (key shape check) + a2 (HTTP verify) +
filesystem I/O + interactive Typer prompts. That's the canonical a4
recipe per AGENTS.md §2 ("CLI handler that wires it all up").
"""

from __future__ import annotations

import os
import stat
from pathlib import Path
from typing import Annotated

import typer

from ..a0_qk_constants.auth_constants import (
    API_KEY_ENV,
    API_KEY_PREFIX,
)
from ..a1_at_functions.forge_auth import is_valid_api_key_shape
from ..a2_mo_composites.forge_auth_client import ForgeAuthClient

CREDENTIALS_DIR = Path("~/.atomadic-forge").expanduser()
CREDENTIALS_FILE = CREDENTIALS_DIR / "credentials.toml"
DASHBOARD_URL = "https://atomadic.tech/forge#account"

app = typer.Typer(
    no_args_is_help=False,
    help="Capture a Forge subscription key and store it in "
         "~/.atomadic-forge/credentials.toml.",
)


def _render_credentials(api_key: str) -> str:
    """Return the TOML body to write. Pure helper — no I/O."""
    # Hand-rolled TOML so we don't add a dependency. The schema is
    # intentionally tiny so future fields can be added without
    # breaking parsers.
    safe = api_key.replace('"', '\\"')
    return (
        "# Atomadic Forge credentials — DO NOT COMMIT.\n"
        "# Generated by `forge login`.\n"
        "[forge_auth]\n"
        f'api_key = "{safe}"\n'
    )


def _write_credentials(path: Path, body: str) -> None:
    """Write credentials atomically with restrictive permissions."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")
    # chmod 600 — only owner can read/write. Best-effort on Windows
    # (NTFS ignores the POSIX bits but the call doesn't raise).
    try:
        os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)
    except OSError:
        pass


@app.callback(invoke_without_command=True)
def login_cmd(
    api_key: Annotated[
        str | None,
        typer.Option(
            "--api-key",
            help="Skip the prompt and use this key directly. Useful "
                 "for CI / scripted setups. Reads from stdin via "
                 "`forge login --api-key -` when set to a single dash.",
        ),
    ] = None,
    no_verify: Annotated[
        bool,
        typer.Option(
            "--no-verify",
            help="Write the key without contacting the verify endpoint. "
                 "Use only for offline bootstrap; the MCP gate will "
                 "still verify on first tool call.",
        ),
    ] = False,
) -> None:
    """Capture a Forge subscription key.

    Without ``--api-key``, prompts interactively; the input is hidden
    and not echoed. With ``--api-key``, takes the key from the flag
    (or stdin when the flag value is ``-``).
    """
    typer.echo("")
    typer.echo("Atomadic Forge — login")
    typer.echo("-" * 60)
    typer.echo(f"  Get a key at: {DASHBOARD_URL}")
    typer.echo(f"  Keys begin with '{API_KEY_PREFIX}'.")
    typer.echo("")

    if api_key == "-":
        api_key = typer.get_text_stream("stdin").read().strip()
    if not api_key:
        api_key = typer.prompt("Paste your Forge API key", hide_input=True)
    api_key = (api_key or "").strip()

    if not is_valid_api_key_shape(api_key):
        typer.secho(
            f"  ✗ key does not match expected shape "
            f"(must start with '{API_KEY_PREFIX}' and have content "
            f"after the prefix).",
            fg="red", err=True,
        )
        raise typer.Exit(code=1)

    email = ""
    plan = ""
    if not no_verify:
        client = ForgeAuthClient()
        result = client.verify(api_key)
        if not result.get("ok"):
            reason = result.get("reason", "verify failed")
            typer.secho(
                f"  ✗ verify endpoint rejected key: {reason}",
                fg="red", err=True,
            )
            raise typer.Exit(code=1)
        email = str(result.get("email", "") or "")
        plan = str(result.get("plan", "") or "")

    body = _render_credentials(api_key)
    _write_credentials(CREDENTIALS_FILE, body)

    typer.echo("")
    if email or plan:
        typer.secho(
            f"  ✓ Logged in as {email or '(unknown email)'} · "
            f"plan: {plan or '(unknown plan)'}",
            fg="green",
        )
    else:
        typer.secho("  ✓ key stored (verification skipped).", fg="yellow")
    typer.echo(f"  credentials: {CREDENTIALS_FILE}")
    typer.echo(f"  hint: export {API_KEY_ENV}=<your-key> "
               f"in your shell profile, or source the file above.")


__all__ = ["app", "login_cmd", "CREDENTIALS_FILE", "DASHBOARD_URL"]
