"""Tier a1 — pure renderers for JS/TS package scaffolds.

Forge's iterate loop scaffolds the surrounding package shell so the LLM
can focus on emitting actual code.  For Python this means ``pyproject.toml``,
``__init__.py``, ``conftest.py``.  For JavaScript / TypeScript it means a
minimal ``package.json`` plus a README — nothing else is required for ES
modules to resolve.

Pure: no I/O.  Each helper returns a string the caller writes to disk.
"""

from __future__ import annotations

import json as _json


def render_package_json(*, package: str, description: str = "",
                          language: str = "javascript") -> str:
    """Render a minimal ``package.json`` for a JS/TS evolved package.

    Sets ``"type": "module"`` so ES6 ``import`` / ``export`` resolves
    natively.  No build step, no dependencies — Forge produces source
    that runs as-is on Node 20+ and Cloudflare Workers.

    The TypeScript variant is identical except for documentation in the
    description (``ts`` files would compile via ``tsc`` or run via
    ``tsx``; that's a downstream concern).
    """
    pkg = {
        "name": package,
        "version": "0.0.1",
        "description": (description or f"{package} — generated by atomadic-forge").strip(),
        "type": "module",
        "private": True,
    }
    return _json.dumps(pkg, indent=2) + "\n"


def render_js_readme(*, package: str, intent: str, language: str) -> str:
    """Render a README.md for a JS/TS evolved package."""
    lang_label = "JavaScript" if language == "javascript" else "TypeScript"
    return (
        f"# {package}\n\n"
        f"{lang_label} package generated by `atomadic-forge evolve`.\n\n"
        f"## Intent\n\n"
        f"{intent.strip() or '(unspecified)'}\n\n"
        f"## Layout (5-tier monadic)\n\n"
        f"- `a0_qk_constants/` — constants, no logic\n"
        f"- `a1_at_functions/` — pure stateless functions\n"
        f"- `a2_mo_composites/` — stateful classes / clients\n"
        f"- `a3_og_features/` — feature orchestrators\n"
        f"- `a4_sy_orchestration/` — entry points (Worker, CLI)\n\n"
        f"Imports compose **upward only** — a lower tier never imports "
        f"from a higher tier.  Forge enforces this in `forge wire`.\n"
    )
