"""Tier a1 — pure renderers for the surrounding package starter files.

Forge scaffolds ``README.md``, ``.gitignore``, ``tests/__init__.py``, and
``tests/conftest.py`` once at iterate Round 0 so the generated package is
a complete, conventional Python project from the first turn.  The LLM
never has to remember to write these — it focuses on the actual code.
"""

from __future__ import annotations


def render_readme(*, package: str, intent: str) -> str:
    safe_intent = intent.strip().replace("`", "'")
    return (
        f"# {package}\n"
        "\n"
        f"_Generated by [Atomadic Forge](https://atomadic.tech) from the intent below._\n"
        "\n"
        "## Intent\n"
        "\n"
        f"> {safe_intent}\n"
        "\n"
        "## Architecture\n"
        "\n"
        "This package follows the Atomadic 5-tier monadic standard:\n"
        "\n"
        "| Tier | Directory | Lives here |\n"
        "|------|-----------|------------|\n"
        "| a0 | `src/" + package + "/a0_qk_constants/` | constants, enums, TypedDicts |\n"
        "| a1 | `src/" + package + "/a1_at_functions/` | pure functions |\n"
        "| a2 | `src/" + package + "/a2_mo_composites/` | stateful classes |\n"
        "| a3 | `src/" + package + "/a3_og_features/` | feature orchestrators |\n"
        "| a4 | `src/" + package + "/a4_sy_orchestration/` | CLI / entry points |\n"
        "\n"
        "## Install\n"
        "\n"
        "```bash\n"
        "pip install -e .\n"
        "```\n"
        "\n"
        "## Run tests\n"
        "\n"
        "```bash\n"
        "pytest tests/\n"
        "```\n"
        "\n"
        "## Verify with Forge\n"
        "\n"
        "```bash\n"
        f"forge wire src/{package}     # zero upward-import violations\n"
        f"forge certify . --package {package}\n"
        "```\n"
    )


def render_gitignore() -> str:
    return (
        "__pycache__/\n"
        "*.py[cod]\n"
        "*.egg-info/\n"
        "build/\n"
        "dist/\n"
        ".venv/\n"
        "venv/\n"
        ".pytest_cache/\n"
        ".ruff_cache/\n"
        ".mypy_cache/\n"
        ".coverage\n"
        ".atomadic-forge/\n"
        ".DS_Store\n"
        ".vscode/\n"
        ".idea/\n"
    )


def render_tests_conftest(*, package: str) -> str:
    return (
        '"""Shared fixtures for ' + package + ' tests."""\n'
        "\n"
        "from __future__ import annotations\n"
        "\n"
        "import sys\n"
        "from pathlib import Path\n"
        "\n"
        "# Make the src/ layout importable when tests run before pip install.\n"
        "ROOT = Path(__file__).resolve().parent.parent\n"
        "SRC = ROOT / 'src'\n"
        "if SRC.exists() and str(SRC) not in sys.path:\n"
        "    sys.path.insert(0, str(SRC))\n"
    )


def render_tests_init() -> str:
    return '"""Tests for the package."""\n'
