"""Tier a1 — pure renderer that builds a stunning README from a generated package.

After evolve converges, Forge walks the produced package and synthesises a
showcase-quality README from the actual code, tests, and certify report.
This replaces the bare scaffolded README with one that reflects what was
actually built — function names, class signatures, working CLI invocation,
score breakdown, evidence.
"""

from __future__ import annotations

import ast
from pathlib import Path
from typing import Any


def _collect_public_symbols(package_root: Path) -> dict[str, list[dict[str, str]]]:
    """Return ``{tier: [{name, kind, signature, doc}]}`` for the package."""
    out: dict[str, list[dict[str, str]]] = {}
    for tier_dir in sorted(package_root.iterdir()):
        if not tier_dir.is_dir():
            continue
        if not tier_dir.name.startswith(("a0_", "a1_", "a2_", "a3_", "a4_")):
            continue
        items: list[dict[str, str]] = []
        for py in sorted(tier_dir.glob("*.py")):
            if py.name == "__init__.py":
                continue
            try:
                tree = ast.parse(py.read_text(encoding="utf-8"))
            except (SyntaxError, OSError):
                continue
            for node in tree.body:
                if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    if node.name.startswith("_"):
                        continue
                    sig = _function_signature(node)
                    items.append({
                        "name": node.name, "kind": "function", "signature": sig,
                        "doc": (ast.get_docstring(node) or "").split("\n")[0],
                        "module": py.stem,
                    })
                elif isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
                    items.append({
                        "name": node.name, "kind": "class",
                        "signature": f"class {node.name}",
                        "doc": (ast.get_docstring(node) or "").split("\n")[0],
                        "module": py.stem,
                    })
        if items:
            out[tier_dir.name] = items
    return out


def _function_signature(fn: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    args: list[str] = []
    for arg in fn.args.args:
        if arg.arg in ("self", "cls"):
            continue
        ann = ast.unparse(arg.annotation) if arg.annotation else None
        args.append(f"{arg.arg}: {ann}" if ann else arg.arg)
    ret = ast.unparse(fn.returns) if fn.returns else "Any"
    return f"def {fn.name}({', '.join(args)}) -> {ret}"


_TIER_LABEL = {
    "a0_qk_constants": "a0 — constants",
    "a1_at_functions": "a1 — pure functions",
    "a2_mo_composites": "a2 — stateful classes",
    "a3_og_features": "a3 — feature orchestrators",
    "a4_sy_orchestration": "a4 — CLI / entry points",
}


def render_showcase_readme(*, package: str, intent: str,
                            output_root: Path,
                            certify_report: dict[str, Any] | None = None,
                            cli_demo: dict[str, Any] | None = None,
                            llm_name: str = "?") -> str:
    """Build a stunning README for a generated package.

    ``cli_demo`` (optional): ``{"command": [...], "stdout": "...", "rc": int}``
    captured from a successful invocation of the generated CLI.
    """
    pkg_root = output_root / "src" / package
    symbols = _collect_public_symbols(pkg_root) if pkg_root.exists() else {}

    # Build a hero score badge from the certify report.
    score_line = ""
    if certify_report:
        score = certify_report.get("score", 0)
        comps = certify_report.get("score_components", {})
        score_line = (
            f"![score](https://img.shields.io/badge/forge_certify-"
            f"{int(score)}%2F100-brightgreen)"
            if score >= 80 else
            f"![score](https://img.shields.io/badge/forge_certify-"
            f"{int(score)}%2F100-yellow)"
        )

    lines: list[str] = [
        f"# `{package}`",
        "",
        score_line,
        "",
        "_Generated by [Atomadic Forge](https://atomadic.tech) — absorb · enforce · emerge._",
        "",
        "## Intent",
        "",
        f"> {intent.strip()}",
        "",
    ]

    if certify_report:
        score = certify_report.get("score", 0)
        comps = certify_report.get("score_components", {})
        smoke = (certify_report.get("detail") or {}).get("import_smoke") or {}
        test_run = (certify_report.get("detail") or {}).get("test_run") or {}
        lines.extend([
            "## Forge certification",
            "",
            f"| Component | Result |",
            f"|-----------|--------|",
            f"| Documentation present | {'✅' if certify_report.get('documentation_complete') else '❌'} |",
            f"| Tests present         | {'✅' if certify_report.get('tests_present') else '❌'} |",
            f"| 5-tier layout         | {'✅' if certify_report.get('tier_layout_present') else '❌'} |",
            f"| Wire (no upward imports) | {'✅' if certify_report.get('no_upward_imports') else '❌'} |",
            f"| Package importable    | {'✅' if certify_report.get('package_importable') else '❌'} |",
            f"| No stub bodies        | {'✅' if certify_report.get('no_stub_bodies') else '❌'} |",
            f"| Tests pass-ratio      | {certify_report.get('test_pass_ratio', 0):.0%} ({test_run.get('passed', 0)}/{test_run.get('total', 0)}) |",
            "",
            f"**Score: {score:.0f}/100** "
            + (f"(structural {comps.get('structural', 0)} · "
                f"runtime {comps.get('runtime', 0)} · "
                f"behavioral {comps.get('behavioral', 0)})"
                if comps else ""),
            "",
        ])

    # Surface the generated symbols, organised by tier.
    if symbols:
        lines.append("## What was built")
        lines.append("")
        for tier in ("a0_qk_constants", "a1_at_functions", "a2_mo_composites",
                      "a3_og_features", "a4_sy_orchestration"):
            if tier not in symbols:
                continue
            lines.append(f"### {_TIER_LABEL[tier]}")
            lines.append("")
            for s in symbols[tier]:
                doc = s["doc"] or ""
                trailer = f" — _{doc}_" if doc else ""
                lines.append(f"- **`{s['signature']}`**{trailer}  "
                              f"<sub>(`{tier}/{s['module']}.py`)</sub>")
            lines.append("")

    if cli_demo:
        lines.extend([
            "## Live invocation",
            "",
            "```bash",
            "$ " + " ".join(cli_demo.get("command", []))[:200],
            (cli_demo.get("stdout") or "").strip()[:500] or "(no stdout)",
            "```",
            "",
            f"Exit code: `{cli_demo.get('rc', '?')}`",
            "",
        ])

    lines.extend([
        "## Architecture",
        "",
        "This package follows the Atomadic 5-tier monadic standard.  Every",
        "file lives in exactly one tier and tiers compose **upward only**.",
        "Every public symbol is reachable via the tier package's "
        "auto-generated `__init__.py` re-exports.",
        "",
        "```",
        f"src/{package}/",
        "├── a0_qk_constants/    constants, enums, TypedDicts",
        "├── a1_at_functions/    pure stateless functions",
        "├── a2_mo_composites/   stateful classes",
        "├── a3_og_features/     feature orchestrators",
        "└── a4_sy_orchestration/ CLI / entry points",
        "```",
        "",
        "## Install",
        "",
        "```bash",
        "pip install -e .",
        "```",
        "",
        "## Verify with Forge",
        "",
        "```bash",
        f"forge wire src/{package}",
        f"forge certify . --package {package}",
        "```",
        "",
        "---",
        "",
        f"_Generated by Atomadic Forge with `{llm_name}` as the generation engine._",
        "",
    ])
    return "\n".join(line for line in lines if line is not None)
