"""Tier a1 — pure renderer for a generated package's ``pyproject.toml``.

When ``forge iterate``/``evolve`` materialises a package, it scaffolds a
real ``pyproject.toml`` so the output is genuinely pip-installable from
moment zero.  The LLM doesn't need to know how to build a pyproject —
Forge does that, and the LLM just emits the ``.py`` files.

The renderer is pure: it takes a name and an optional console-script
target and returns a TOML string.
"""

from __future__ import annotations

from collections.abc import Iterable


def render_pyproject(
    *,
    package: str,
    description: str = "",
    version: str = "0.1.0",
    python_requires: str = ">=3.10",
    console_script_target: str | None = None,
    extra_dependencies: Iterable[str] = (),
) -> str:
    """Return a PEP-621 pyproject.toml as a string.

    ``console_script_target``: e.g. ``"a4_sy_orchestration.cli:main"``.
    The script becomes ``<package> = "<package>.<target>"`` so users can
    run ``<package>`` after install.
    """
    desc = (description or f"{package} — generated by atomadic-forge").replace('"', "'")
    deps = ",\n    ".join(f'"{d}"' for d in extra_dependencies)
    deps_block = (
        f"dependencies = [\n    {deps},\n]\n" if deps else "dependencies = []\n"
    )
    scripts_block = ""
    if console_script_target:
        scripts_block = (
            "\n[project.scripts]\n"
            f'{package} = "{package}.{console_script_target}"\n'
        )

    return (
        "# Auto-scaffolded by atomadic-forge.  Edit freely.\n"
        "[build-system]\n"
        'requires = ["setuptools>=68", "wheel"]\n'
        'build-backend = "setuptools.build_meta"\n'
        "\n"
        "[project]\n"
        f'name = "{package}"\n'
        f'version = "{version}"\n'
        f'description = "{desc}"\n'
        f'readme = "README.md"\n'
        f'requires-python = "{python_requires}"\n'
        + deps_block
        + scripts_block
        + "\n"
        "[tool.setuptools.packages.find]\n"
        'where = ["src"]\n'
        f'include = ["{package}*"]\n'
    )
