"""Tier a1 — deterministic quality phases for generated packages.

These helpers run after an LLM has emitted code.  They do not invent
business behavior; they add baseline documentation, docstrings, and import
smoke tests so generated packages start with a usable maintenance surface.
"""

from __future__ import annotations

import ast
from pathlib import Path
from typing import Any

from ..a0_qk_constants.tier_names import TIER_NAMES

_GENERATED_MARKER = "<!-- generated by atomadic-forge quality phase -->"

_TIER_LABELS = {
    "a0_qk_constants": "constants and type shapes",
    "a1_at_functions": "pure functions",
    "a2_mo_composites": "stateful composites",
    "a3_og_features": "feature orchestration",
    "a4_sy_orchestration": "entry points and CLI wiring",
}


def apply_docstring_phase(package_root: Path) -> dict[str, Any]:
    """Add conservative docstrings to Python modules missing them."""
    package_root = Path(package_root)
    changed: list[str] = []
    scanned = 0
    if not package_root.exists():
        return {"phase": "docstrings", "language": "python",
                "files_scanned": 0, "files_changed": []}
    for path in sorted(package_root.rglob("*.py")):
        if "__pycache__" in path.parts or path.name == "__init__.py":
            continue
        scanned += 1
        try:
            original = path.read_text(encoding="utf-8")
        except OSError:
            continue
        updated = add_missing_docstrings(original, rel_path=path.relative_to(package_root))
        if updated != original:
            path.write_text(updated, encoding="utf-8")
            changed.append(path.relative_to(package_root).as_posix())
    return {"phase": "docstrings", "language": "python",
            "files_scanned": scanned, "files_changed": changed}


def add_missing_docstrings(source: str, *, rel_path: Path | str) -> str:
    """Return ``source`` with missing module/class/function docstrings added."""
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return source
    lines = source.splitlines()
    if not lines:
        return source
    rel = Path(rel_path).as_posix()
    inserts: list[tuple[int, str]] = []

    if ast.get_docstring(tree) is None:
        inserts.append((0, f'"""{_module_docstring(rel)}"""'))

    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef):
            if node.name.startswith("_") or ast.get_docstring(node) is not None:
                continue
            inserts.append(_docstring_insert(node, _class_docstring(node.name)))
        elif isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            if node.name.startswith("_") and node.name != "__init__":
                continue
            if ast.get_docstring(node) is not None:
                continue
            inserts.append(_docstring_insert(node, _function_docstring(node.name)))

    for index, text in sorted(inserts, key=lambda item: item[0], reverse=True):
        lines.insert(index, text)
    return "\n".join(lines) + ("\n" if source.endswith("\n") else "")


def _docstring_insert(node: ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef,
                      text: str) -> tuple[int, str]:
    if not node.body:
        return (node.lineno, f'    """{text}"""')
    first = node.body[0]
    indent = " " * getattr(first, "col_offset", 4)
    return (max(0, first.lineno - 1), f'{indent}"""{text}"""')


def _module_docstring(rel: str) -> str:
    tier = next((part for part in rel.split("/") if part in TIER_NAMES), "")
    label = _TIER_LABELS.get(tier, "generated package code")
    stem = Path(rel).stem.replace("_", " ")
    return f"{label.capitalize()} for {stem}."


def _class_docstring(name: str) -> str:
    words = _humanize_name(name)
    return f"Coordinate {words} behavior."


def _function_docstring(name: str) -> str:
    if name == "__init__":
        return "Initialize the instance."
    words = _humanize_name(name)
    if name.startswith(("is_", "has_", "can_", "should_")):
        return f"Return whether {words}."
    if name.startswith(("parse_", "load_", "read_")):
        return f"Parse {words} input."
    if name.startswith(("render_", "format_", "build_")):
        return f"Build {words} output."
    if name.startswith(("validate_", "check_")):
        return f"Validate {words}."
    return f"Run the {words} operation."


def _humanize_name(name: str) -> str:
    if name == "__init__":
        return "instance"
    out: list[str] = []
    current = ""
    for ch in name.replace("_", " "):
        if ch.isupper() and current and not current.endswith(" "):
            out.append(current)
            current = ch.lower()
        else:
            current += ch.lower()
    if current:
        out.append(current)
    return " ".join("".join(out).split())


def apply_docs_phase(*, output_root: Path, package_root: Path,
                     package: str, intent: str) -> dict[str, Any]:
    """Create generated API and testing docs without overwriting custom docs."""
    docs_dir = Path(output_root) / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)
    written: list[str] = []
    skipped: list[str] = []
    files = {
        docs_dir / "API.md": render_api_doc(package_root=package_root,
                                             package=package, intent=intent),
        docs_dir / "TESTING.md": render_testing_doc(package=package),
    }
    for path, content in files.items():
        if _write_generated(path, content):
            written.append(path.relative_to(output_root).as_posix())
        else:
            skipped.append(path.relative_to(output_root).as_posix())
    return {"phase": "docs", "files_written": written, "files_skipped": skipped}


def render_api_doc(*, package_root: Path, package: str, intent: str) -> str:
    """Render a compact API reference from public Python symbols."""
    symbols = _collect_symbols(package_root)
    lines = [
        _GENERATED_MARKER,
        f"# {package} API",
        "",
        "This reference is generated from the package source after the Forge",
        "quality phase has added missing docstrings.",
        "",
        "## Intent",
        "",
        f"> {intent.strip() or '(unspecified)'}",
        "",
    ]
    if not symbols:
        lines.extend([
            "## Public Surface",
            "",
            "No public Python symbols were discovered yet.",
            "",
        ])
    for tier in TIER_NAMES:
        items = symbols.get(tier, [])
        if not items:
            continue
        lines.extend([f"## {tier}", ""])
        for item in items:
            doc = f" — {item['doc']}" if item["doc"] else ""
            lines.append(f"- `{item['signature']}`{doc} (`{item['module']}`)")
        lines.append("")
    return "\n".join(lines)


def render_testing_doc(*, package: str) -> str:
    """Render generated testing guidance for the package."""
    return "\n".join([
        _GENERATED_MARKER,
        f"# Testing {package}",
        "",
        "Forge creates a baseline import-smoke test so every generated module",
        "is at least importable. Treat it as a floor, not a substitute for",
        "behavioral tests against real inputs.",
        "",
        "```bash",
        "pytest tests/",
        f"forge certify . --package {package}",
        "```",
        "",
        "Add focused tests beside `tests/test_generated_smoke.py` as the",
        "package behavior becomes clearer.",
        "",
    ])


def apply_test_phase(*, output_root: Path, package_root: Path,
                     package: str) -> dict[str, Any]:
    """Create or refresh the generated import-smoke test."""
    tests_dir = Path(output_root) / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)
    target = tests_dir / "test_generated_smoke.py"
    content = render_smoke_test(package_root=package_root, package=package)
    target.write_text(content, encoding="utf-8")
    return {"phase": "tests",
            "files_written": [target.relative_to(output_root).as_posix()],
            "module_count": len(_module_names(package_root, package))}


def render_smoke_test(*, package_root: Path, package: str) -> str:
    """Render a stdlib-only pytest-compatible import-smoke test."""
    modules = _module_names(package_root, package)
    module_lines = "\n".join(f"    {name!r}," for name in modules)
    package_import = (
        f"import {package} as generated_package"
        if package.isidentifier()
        else f"generated_package = importlib.import_module({package!r})"
    )
    import_lines = ["import importlib", "", package_import]
    return "\n".join([
        f'"""Generated import-smoke tests for {package}."""',
        "",
        "from __future__ import annotations",
        "",
        *import_lines,
        "",
        "MODULES = [",
        module_lines,
        "]",
        "",
        "",
        "def test_generated_package_imports():",
        "    assert generated_package",
        "",
        "",
        "def test_generated_modules_import():",
        "    for module_name in MODULES:",
        "        assert importlib.import_module(module_name)",
        "",
    ])


def _write_generated(path: Path, content: str) -> bool:
    if path.exists():
        existing = path.read_text(encoding="utf-8", errors="replace")
        if _GENERATED_MARKER not in existing:
            return False
    path.write_text(content, encoding="utf-8")
    return True


def _module_names(package_root: Path, package: str) -> list[str]:
    out = [package]
    if package_root.exists():
        for py in sorted(package_root.rglob("*.py")):
            if "__pycache__" in py.parts or py.name == "__init__.py":
                continue
            rel = py.relative_to(package_root).with_suffix("")
            parts = ".".join(rel.parts)
            out.append(f"{package}.{parts}")
    return sorted(dict.fromkeys(out))


def _collect_symbols(package_root: Path) -> dict[str, list[dict[str, str]]]:
    out: dict[str, list[dict[str, str]]] = {}
    if not package_root.exists():
        return out
    for tier in TIER_NAMES:
        tier_dir = package_root / tier
        if not tier_dir.exists():
            continue
        items: list[dict[str, str]] = []
        for py in sorted(tier_dir.glob("*.py")):
            if py.name == "__init__.py":
                continue
            try:
                tree = ast.parse(py.read_text(encoding="utf-8"))
            except (SyntaxError, OSError):
                continue
            module = f"{tier}/{py.name}"
            for node in tree.body:
                if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
                    items.append({
                        "module": module,
                        "signature": f"class {node.name}",
                        "doc": _first_doc_line(node),
                    })
                elif isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
                    if node.name.startswith("_"):
                        continue
                    items.append({
                        "module": module,
                        "signature": _signature(node),
                        "doc": _first_doc_line(node),
                    })
        if items:
            out[tier] = items
    return out


def _first_doc_line(node: ast.AST) -> str:
    doc = ast.get_docstring(node) or ""
    return doc.strip().split("\n", 1)[0] if doc else ""


def _signature(fn: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    args = [a.arg for a in fn.args.args if a.arg not in {"self", "cls"}]
    prefix = "async def" if isinstance(fn, ast.AsyncFunctionDef) else "def"
    return f"{prefix} {fn.name}({', '.join(args)})"
